plugins {
    id 'com.android.application'
}

android {
    namespace 'com.ichochy.nce3'
    compileSdk 34

    defaultConfig {
        applicationId "com.ichochy.nce3"
        minSdk 21
        targetSdk 34
        versionCode 1
        versionName "1.0"
    }

    buildTypes {
        release {
            minifyEnabled false
            signingConfig signingConfigs.debug
        }
    }
}

dependencies {
    implementation 'androidx.appcompat:appcompat:1.6.1'
}
